.github/workflows/deploy.yml, build.gradle
https://github.com/fofo-project/fofo-backend/actions/runs/8470894215
feature 브랜치에서 정상 동작 확인
=> Github Actions 활용한 CI/CD 구축

src/main/java/com/fofo/core/config/WebConfig.java
```@Configuration(proxyBeanMethods = false)
public class WebConfig implements WebMvcConfigurer {
@Override
public void addCorsMappings(final CorsRegistry registry) {
registry.addMapping("/**")
.allowedOrigins("http://144.24.85.213:5173")
.allowedMethods("*");
}
}```
=> cors 이슈 관련 서버측 예외처리 적용

src/main/java/com/fofo/core/controller/request/AppendMemberRequestDto.java, src/main/java/com/fofo/core/controller/request/FindMembersConditionDto.java, src/main/java/com/fofo/core/controller/response/FindMemberResponseDto.java, src/main/java/com/fofo/core/domain/match/MatchManager.java, src/main/java/com/fofo/core/domain/member/AgeRelationType.java, src/main/java/com/fofo/core/domain/member/FilteringSmoker.java, src/main/java/com/fofo/core/domain/member/Gender.java, src/main/java/com/fofo/core/domain/member/MemberFinder.java, src/main/java/com/fofo/core/domain/member/SmokingYn.java, src/main/java/com/fofo/core/storage/MemberEntity.java, src/main/java/com/fofo/core/storage/converter/GenderConverter.java
=> 프론트엔드측 API 요구사항 반영

src/main/java/com/fofo/core/controller/MemberController.java, src/main/java/com/fofo/core/controller/request/MembersRequestDto.java, src/main/java/com/fofo/core/controller/response/MembersResponseDto.java, src/main/java/com/fofo/core/domain/member/MemberService.java, src/main/java/com/fofo/core/domain/member/MemberUpdater.java
- 멤버 삭제 API(=가입 거절)
- 멤버 가입 확정 API
closes #37.
=> member 다건 상태변화 API 추가

src/main/java/com/fofo/core/controller/MemberController.java, src/main/java/com/fofo/core/controller/request/DepositRequestMemberDto.java, src/main/java/com/fofo/core/domain/member/MemberService.java, src/main/java/com/fofo/core/domain/member/MemberUpdater.java
=> 다건 상태변화 API 추가

src/main/resources/application.yml
- 443 > 8080 (443포트 권한 이슈로 포트 원복)
=> https 포트 변경

src/main/java/com/fofo/core/config/WebConfig.java, src/main/java/com/fofo/core/controller/MemberController.java
- https://fofo.world:443, https://dev-fofo.world:443 origin 추가
- 일부 swagger summary 문구 수정
=> Cors 허용 Origin 추가

src/main/java/com/fofo/core/domain/member/AgeRelationType.java, src/main/java/com/fofo/core/domain/member/FilteringSmoker.java, src/main/java/com/fofo/core/storage/converter/AgeRelationTypeConverter.java, src/main/java/com/fofo/core/storage/converter/FilteringSmokerConverter.java, src/main/java/com/fofo/core/storage/converter/ReligionConverter.java, src/main/java/com/fofo/core/storage/converter/SmokingYnConverter.java
- jpa converter nullable 필드 처리 개선
closes #49
=> JPA converter nullable 필드 처리 개선

src/main/java/com/fofo/core/controller/request/MatchRequestDto.java, src/main/java/com/fofo/core/domain/match/MatchUpdater.java, src/main/java/com/fofo/core/storage/MemberMatchEntity.java
매칭다음단계 api
- requestDto agreement 타입 Boolean -> MatchAgreement enum 변경 
- membermatch 엔티티 agreement 컬럼 setter 추가
This closes #52
=> 매칭다음단계 api 동의 추가 관련 수정

src/main/java/com/fofo/core/storage/MatchCustomRepositoryImpl.java, src/main/java/com/fofo/core/storage/MemberCustomRepositoryImpl.java
depositDate.desc() -> depositDate.asc()
멤버 조회 두번째 정렬조건 생성일 오름차순으로 조회
This closes #54
=> 멤버조회 정렬조건 변경

src/main/resources/application.yml
- 로깅
- ssl
- 개발 DB jdbc config
closes #56
=> dev profile 추가

src/main/java/com/fofo/core/controller/request/AppendMemberRequestDto.java, src/main/java/com/fofo/core/storage/MemberEntity.java, src/main/java/com/fofo/core/storage/converter/FilteringSmokerConverter.java
=> #63-FilteringSmoker not null 속성으로 변경

src/main/java/com/fofo/core/domain/match/MatchManager.java
=> #65-match 나이조건 필터 반대 수정

src/main/java/com/fofo/core/controller/request/AppendMemberRequestDto.java, src/main/java/com/fofo/core/controller/request/MatchRequestDto.java, src/main/java/com/fofo/core/domain/image/ImageType.java, src/main/java/com/fofo/core/domain/match/MatchFinder.java, src/main/java/com/fofo/core/domain/match/MatchService.java, src/main/java/com/fofo/core/domain/match/MatchUpdater.java, src/main/java/com/fofo/core/domain/member/MemberFinder.java, src/main/java/com/fofo/core/domain/member/MemberUpdater.java, src/main/java/com/fofo/core/storage/AddressEntity.java, src/main/java/com/fofo/core/storage/HashtagEntity.java, src/main/java/com/fofo/core/storage/MemberEntity.java, src/main/java/com/fofo/core/storage/MemberImageEntity.java, src/main/java/com/fofo/core/storage/MemberMatchEntity.java, src/main/java/com/fofo/core/storage/MemberRepository.java, src/main/resources/application.yml
- Member 최초 생성시 MatchableYn='N', APPROVED 되면 MatchableYn='Y'
- MATCH_COMPLETED 되고 chance 전부 소진시 해당 member 입금 전 상태로 롤백
- 둘 다 동의해서 MATCHING_COMPLETD 되면 남여 각각 찬스 1개 소진
- 인덱스 추가
- 수정대상 Class 내부 선언 순서 컨벤션 반영(static 변수 - 인스턴스 변수 - staitc 메서드 - 생성자 - 인스턴스 메서드(일반 메서드) - getter(), setter(), toString()
closes #68
=> 단위테스트 개선사항 반영

src/main/java/com/fofo/core/domain/member/MemberFinder.java, src/main/java/com/fofo/core/storage/MatchCustomRepository.java, src/main/java/com/fofo/core/storage/MatchCustomRepositoryImpl.java, src/main/java/com/fofo/core/storage/MemberRepository.java
=> 매칭 대상 member 조회 시 입금순 정렬 추가2

src/main/java/com/fofo/core/storage/MemberEntity.java
=> 찬스 다 소진시 MatchableYn = 'N' 처리 추가

build.gradle, src/main/java/com/fofo/core/controller/MemberController.java, src/main/java/com/fofo/core/controller/request/AppendMemberRequestDto.java, src/main/java/com/fofo/core/controller/request/UpdateMemberRequestDto.java, src/main/java/com/fofo/core/domain/member/MemberAppender.java, src/main/java/com/fofo/core/domain/member/MemberService.java, src/main/java/com/fofo/core/domain/member/MemberUpdater.java, src/main/resources/application.yml
=> member 등록/수정 API 이미지 첨부 추가

src/main/java/com/fofo/core/controller/MemberController.java
- consumes = MediaType.MULTIPART_FORM_DATA_VALUE
=> member 수정 API 누락 코드 추가

src/main/java/com/fofo/core/controller/MemberController.java, src/main/java/com/fofo/core/controller/request/AppendMemberRequestDto.java, src/main/java/com/fofo/core/controller/response/FindMemberResponseDto.java, src/main/java/com/fofo/core/domain/image/Image.java, src/main/java/com/fofo/core/domain/member/Form.java, src/main/java/com/fofo/core/domain/member/FormFinder.java, src/main/java/com/fofo/core/domain/member/FormService.java, src/main/java/com/fofo/core/domain/member/MemberFinder.java, src/main/java/com/fofo/core/domain/member/MemberService.java, src/main/java/com/fofo/core/storage/ImageRepository.java, src/main/java/com/fofo/core/storage/MemberImageEntity.java
- userProfileImages 리스트 추가
- profileCardImage 값 추가
=> member 조회 API 응답값에 이미지 정보 추가

src/main/java/com/fofo/core/domain/image/FileStore.java, src/main/java/com/fofo/core/domain/member/MemberUpdater.java, src/main/java/com/fofo/core/storage/MemberImageEntity.java, src/main/java/com/fofo/core/support/error/CoreErrorCode.java, src/main/java/com/fofo/core/support/error/CoreErrorType.java
- 프로필 카드 이미지 업데이트시 update 처리 추가
- uploadFile null 처리 개선
=> 이미지 파일 업데이트 개선

src/main/java/com/fofo/core/domain/image/FileStore.java, src/main/java/com/fofo/core/support/error/CoreErrorCode.java, src/main/java/com/fofo/core/support/error/CoreErrorType.java
This reverts commit 9d7a1c851ca98b08b11a8c5870d0c9be63509151.
=> 파일 null 관련 에러 처리 추가 revert!

.github/workflows/deploy.yml
=> github action 오류 수정

src/main/resources/logback-spring.xml
=> logback 로그 경로 환경변수 설정

src/main/java/com/fofo/core/domain/member/MemberUpdater.java
- MultipartFile.isEmpty() 동작방식 이해필요 -> null체크 아님
=> 파일 업로드 관련 null 처리 개선

.github/workflows/deploy.yml, src/main/resources/application.yml, src/main/resources/logback-spring.xml
- applcation.yml의 log관련 설정 logback-spring.xml 로 이전, local 환경에선 console 로그로 수정
- appliation.yml 공통 설정 위치 수정
- deploy.xml 에서 deprecated 된 설정값 변경
closes #100
=> #100-logback 설정 개선

src/main/java/com/fofo/core/storage/MatchCustomRepositoryImpl.java
생성 내림차순 -> 수정 내림차순 으로 변경
This closes #102
=> 매치결과조회 정렬 수정

src/main/java/com/fofo/core/domain/image/FileStore.java, src/main/java/com/fofo/core/domain/member/MemberRemover.java, src/main/java/com/fofo/core/domain/member/MemberService.java, src/main/java/com/fofo/core/domain/member/MemberUpdater.java, src/main/java/com/fofo/core/storage/MemberImageEntity.java
- 가입 거절 시 등록된 이미지 삭제 기능 추가
- 프로필 카드 이미지 업데이트 되면 이전 이미지 삭제 기능 추가
closes #74
=> 이미지 파일 관리 개선

src/main/java/com/fofo/core/domain/match/MatchUpdater.java
- 매칭 동의한 경우 MatchableYn 값 'N' 에서 'Y'로 설정 추가
=> 매칭 동의시 MatchableYn 값 오류로 인해 회원관리에서 조회 불가 오류 수정

src/main/resources/application.yml
=> #104-hikari pool connection-timeout 설정

src/main/java/com/fofo/core/domain/match/Match.java, src/main/java/com/fofo/core/domain/match/MatchAppender.java, src/main/java/com/fofo/core/domain/match/MatchFinder.java, src/main/java/com/fofo/core/domain/match/MatchManager.java, src/main/java/com/fofo/core/domain/match/MatchMemberIdPair.java, src/main/java/com/fofo/core/domain/match/MatchService.java, src/main/java/com/fofo/core/domain/match/MatchWithMember.java, src/main/java/com/fofo/core/domain/member/MemberUpdater.java, src/main/java/com/fofo/core/storage/MatchCustomRepository.java, src/main/java/com/fofo/core/storage/MatchCustomRepositoryImpl.java
- 완료된 매치나 취소된 매치 중 남녀멤버 중복 매치는 재매치 불가
- 찬스남은 멤버 매칭가능 되돌리기 버그 수정
- 초기 매치 생성 시 default 동의값 null
=> 자동매치 중 중복 재매치 불가하도록 변경
